### ISSUE TITLE
主页草图设计

### ISSUE THREAD

**Issue by Xkimnt** [255-1/SpiderJob-BigData#10]
[主页草图设计.zip](https://github.com/255-1/JobMatching/files/3956219/default.zip)

👨 简单弄了一下。文件里包括一份精美设计图和主页的html，将就看。如果觉得这样的结构可以，我在做概要设计

**Comment by 255-1** [comment]
ok

**Comment by WingLee6** [comment]
get

**Comment by WingLee6** [comment]
1. 二级菜单；
2. 大部分组件写了已经有备注；
3. 部分布局没有完善，仅简单实现；
4. 没有美化
5. 页面布局
![image](https://user-images.githubusercontent.com/45314172/70738130-17f86c80-1d4f-11ea-9430-3eb17483e9de.png)


[未命名文件夹.zip](https://github.com/255-1/JobMatching/files/3957246/default.zip)
