### ISSUE TITLE
关于1.0

### ISSUE THREAD

**Issue by Xkimnt** [255-1/SpiderJob-BigData#9]
今天发现1.0的前进和后退键的功能当时漏做了...现在做好了，而且现在能标识当前处于哪一页。那么是把这个版本加到1.1吗？

**Comment by 255-1** [comment]
前进和后退是啥。。。

**Comment by Xkimnt** [comment]
就分页的前进和后退键,当时加的时候感觉没什么必要,结果忘改了。

**Comment by 255-1** [comment]
里程碑就别动了
